t_social_med/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views
from cursos import views as cursos_views
from talleres import views as talleres_views
from prevencion import views as prevencion_views
from cursos.views import Detalle
from cursos.views import Coment
from talleres.views import Detalletaller
from cursos.views import enviarcomentario
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',
         core_views.home, name='Home'),
    path('', include('users.urls', namespace='users')),
    path('olvidar_contrasena/', core_views.olvidar_contrasena,
         name='olvidar_contrasena'),
    path('recuperar_clave/', core_views.recuperar_clave, name='recuperar_clave'),
    path('contacto/', core_views.contacto, name='contacto'),
    path('docentes/', core_views.docentes, name='docentes'),
    path('cursos/', cursos_views.cursos, name='cursos'),
    path('talleres/', talleres_views.talleres, name='talleres'),
    path('prevencion/', prevencion_views.prevencion, name='prevencion'),
    path('informacion_curso/<int:pk>/',
         Detalle.as_view(), name='informacion_curso'),
    path('confirmacion_curso/', cursos_views.confirmacion,
         name='confirmacion_curso'),
     path('informacion_taller/<int:pk>/',Detalletaller.as_view(),name='informacion_taller'),
    path('enviar_correo_contacto/', core_views.enviar_correo_contacto,
         name='enviar_correo_contacto'),
    path('inicio_sesion/', users_views.inicio_sesion, name='inicio_sesion'),
    path('form_registro/', users_views.registro, name='form_registro'),
    path('eliminar_cuenta/', core_views.eliminar_cuenta, name='eliminar_cuenta'),
    path('registrar_datos/', users_views.signup_view, name='registrar_datos'),
    path('aviso_cookies/', core_views.aviso_cookies, name='aviso_cookies'),
    path('comentarios/', Coment.as_view(), name='comentarios'),
    path('enviarcomentario/', cursos_views.enviarcomentario,
         name='enviarcomentario'),
    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('inicio_sesion/', views.inicio_sesion, name='inicio_sesion'),
    path('login/', views.login_view, name='login'),
    path('form_registro/', views.registro, name='form_registro'),
    path('signup/', views.signup_view, name='signup'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('logout/', views.logout_view, name='logout'),
]

core/models.py
from django.db import models
# aca se importa el username interno de django
from django.contrib.auth.models import User
from datetime import datetime
from users.models import UserProfile


class Usuarios(models.Model):
    username = models.OneToOneField(
        UserProfile, verbose_name="username", on_delete=models.CASCADE, null=False)
    nombre = models.CharField(max_length=40, verbose_name="Nombre", null=False)
    apellido = models.CharField(
        max_length=40, verbose_name="Apellidos", default="Apellido", null=False)
    nac = models.DateField(verbose_name="Fecha de Nacimiento",
                           default=datetime.now, null=False)
    zona = models.CharField(
        max_length=20, verbose_name="Ciudad", default='zona', null=False)
    correo = models.EmailField(
        max_length=30, verbose_name="Direccion de correo", null=False)
    telefono = models.CharField(
        max_length=20, verbose_name="Numero Telefonico", null=False)
    imagen = models.ImageField(
        upload_to='media/', verbose_name="Imagen", null=True)
    trabajo = models.CharField(
        max_length=30, verbose_name="Ocupacion", default="Ocupacion", null=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

cursos/models.py
from django.utils import timezone
from django.db import models
# aca se importa el username interno de django
from django.contrib.auth.models import User
from datetime import datetime
from users.models import UserProfile


class Cursos(models.Model):
    titulo = models.CharField(max_length=80, verbose_name="Nombre del curso")
    presentacion = models.TextField(verbose_name="Presentación del curso")
    image = models.ImageField(
        upload_to='media/', verbose_name="Imagen", default='assets/default.jpg', null=True)
    competencias = models.TextField(
        verbose_name="Competencias que vas a adquirir")
    objetivos = models.TextField(verbose_name="Objetivo")
    dirigido = models.TextField(verbose_name="Dirigido a")
    mod_dur_valor = models.TextField(
        verbose_name="Modalidad, duración y valor")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ["-created"]

    # para que en el admin se le coloquen los titulos de las noticias
    def __str__(self):
        return self.titulo


class Inscripcion(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(
        verbose_name="Fecha de inscripcion", default=timezone.now, blank=True)
    user = models.ForeignKey(
        UserProfile, verbose_name="Usuario", on_delete=models.CASCADE, null=False)
    curso = models.ForeignKey(
        Cursos, verbose_name="Curso", on_delete=models.CASCADE, null=False)

    def __str__(self):
        return str(self.curso)

    class Meta:
        verbose_name = "Inscripcion"
        verbose_name_plural = "Inscripciones"


class Comentario(models.Model):
    curso = models.ForeignKey(Cursos, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    calificacion = models.IntegerField()
    comentario = models.TextField()
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.nombre} - {self.fecha_publicacion}'

prevencion/models.py
from django.db import models

class Prevencion(models.Model):
    titulo = models.CharField(
        max_length=80, verbose_name="Nombre del curso")
    presentacion = models.TextField(verbose_name="Presentación del curso")
    competencias = models.TextField(
        verbose_name="Competencias que vas a adquirir")
    objetivos = models.TextField(verbose_name="Objetivo")
    dirigido = models.TextField(verbose_name="Dirigido a")
    mod_dur_valor = models.TextField(
        verbose_name="Modalidad, duración y valor")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Prevención"
        verbose_name_plural = "Prevención"
        ordering = ["-created"]

    # para que en el admin se le coloquen los titulos de las noticias
    def __str__(self):
        return self.titulo

talleres/models.py
from django.db import models


class Talleres(models.Model):
    titulo = models.CharField(
        max_length=200, verbose_name="Nombre del taller")
    presentacion = models.TextField(verbose_name="Presentación del taller")
    competencias = models.TextField(
        verbose_name="Competencias que vas a adquirir")
    image = models.ImageField(
        upload_to='media/', verbose_name="Imagen", default='assets/default.jpg', null=True)
    objetivos = models.TextField(verbose_name="Objetivo")
    dirigido = models.TextField(verbose_name="Dirigido a")
    mod_dur_valor = models.TextField(
        verbose_name="Modalidad, duración y valor")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Taller"
        verbose_name_plural = "Talleres"
        ordering = ["-created"]

    # para que en el admin se le coloquen los titulos de las noticias
    def __str__(self):
        return self.titulo

core/views.py
import time

from django.shortcuts import render, redirect
from django.http import HttpResponse
from t_social_med.enviarCorreo import funcionEnviarCorreo, enviarCorreoContacto, funcionRecuperarPassword
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.conf import settings
from django.shortcuts import render



def home(request):
    # capturamos la id del usuario que se logee en la pagina
    request.session['usuario'] = request.user.id
    usuario_autenticado = request.user.is_authenticated
    var1 = time.time()

    data = {
        'titulo': 'titulo correo',
        'correoDestino': ['vravest@gmail.com'],
        'curso': 'manejo de la ira',
    }

    return render(request, 'core/home.html', {'var1': var1, 'usuario_autenticado': usuario_autenticado})


def contacto(request):
    if request.user.is_authenticated:
        request.session['usuarionombre'] = request.user.nombre
        request.session['usuarioCorreo'] = request.user.email
    var1 = time.time()
    return render(request, 'core/contacto.html', {'var1': var1})


def docentes(request):
    var1 = time.time()
    return render(request, 'core/docentes.html', {'var1': var1})


def olvidar_contrasena(request):
    if request.method == 'POST':
        destinatario = {
            'email': request.POST.get('ingCorreo', ''),
        }
        funcionRecuperarPassword(destinatario)
        return HttpResponse("Correo enviado.")
    else:
        return render(request, 'core/olvidar_contrasena.html')

    var1 = time.time()
    return render(request, 'core/olvidar_contrasena.html', {'var1': var1})


def recuperar_clave(request):
    var1 = time.time()
    return render(request, 'core/recuperar_clave.html', {'var1': var1})


# def informacion_curso(request):
#     var1 = time.time()
#     return render(request, 'core/informacion_curso.html', {'var1': var1})




def enviar_correo_contacto(request):
    if request.method == 'POST':
        datos_formulario = {
            'nombre': request.POST.get('txtName', ''),
            'email': request.POST.get('txtEmail', ''),
            'mensaje': request.POST.get('txtMsg', ''),
        }
        enviarCorreoContacto(datos_formulario)
        return JsonResponse({'message': 'Correo enviado correctamente. Gracias por contactarnos.'})
    else:
        return render(request, 'core/contacto.html')

    

@login_required
def eliminar_cuenta(request):
    if request.method == 'POST':
        try:
            user = request.user
            user.delete()

            # Envía una respuesta JSON indicando éxito
            return JsonResponse({'title': 'Éxito', 'message': 'Tu cuenta ha sido eliminada exitosamente.', 'icon': 'success'})
        except Exception as e:
            return JsonResponse({'title': 'Error', 'message': f'Ocurrió un error: {str(e)}', 'icon': 'error'})

    return render(request, 'users/eliminar_cuenta.html')


def reportes(request):
    var1 = time.time()
    return render(request, 'core/reportes.html', {'var1': var1})




def aviso_cookies(request):
    var1 = time.time()
    return render(request, 'core/aviso_cookies.html', {'var1': var1})

cursos/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.views.generic import ListView
from .models import Cursos
from .models import Inscripcion
from .models import Comentario
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.db.models import Q
from t_social_med.enviarCorreo import enviarCorreoConfirmacionInscripcion
# from openpyxl import Workbook


def cursos(request):
    if request.user.is_authenticated:
        request.session['usuario'] = request.user.id
        busqueda = request.POST.get('txt_busqueda', '')
        print(busqueda)
        if busqueda:
            cur = Cursos.objects.filter(
                Q(titulo__icontains=busqueda) | Q(presentacion__icontains=busqueda)
            )
        else:
            # If no search term is provided, get all objects
            cur = Cursos.objects.all()

        return render(request, 'core/cursos.html', {'cur': cur, 'busqueda': busqueda})
    else:
        return redirect('inicio_sesion')


class Detalle(DetailView):  # Esta clase permite que se vea el detalle del curso para cada curso
    model = Cursos
    template_name = 'core/informacion_curso.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curso = self.object  # La instancia del curso actual

        # Verificar si el usuario actual está inscrito en este curso
        esta_inscrito = Inscripcion.objects.filter(
            curso=curso, user=self.request.user).exists()

        # Agregar la información al contexto
        context['esta_inscrito'] = esta_inscrito
        return context


@login_required(login_url='inicio_sesion')
def confirmacion(request):
    if request.method == 'GET':
        a = request.GET.get('valor')
        v = [a]
        return render(request, 'core/confirmacion_curso.html', {'variable': v})

    if request.method == 'POST':
        print("entre post")
        print(request.POST['valor'])
        us = request.user.id
        c = request.POST['valor']

        # Obtener el curso
        curso = get_object_or_404(Cursos, pk=c)

        # Obtener el usuario actual
        usuario = request.user.id

        # Verificar si el usuario está inscrito en el curso
        esta_inscrito = Inscripcion.objects.filter(
            curso=curso, user=usuario).exists()
        print(esta_inscrito)

        if (esta_inscrito):
            return JsonResponse({"resp": "inscripcion_existe", "mensaje": "Ya te encuentra inscrito."}, status="200")

        formulario = Inscripcion(user_id=us, curso_id=c)
        formulario.save()

        # Obtener el correo del usuario
        correo_usuario = request.user.email

        # Luego de guardar la inscripción, enviar el correo de confirmación
        enviarCorreoConfirmacionInscripcion(correo_usuario, curso.titulo, correo_usuario)

        return JsonResponse({"resp": "inscripcion_ok", "mensaje": "Te has inscrito correctamente."}, status="200")


class Coment(ListView):
    model = Comentario
    template_name = 'core/comentarios.html'
    context_object_name = 'comentarios'

    def get_queryset(self):
        return Comentario.objects.all().order_by('-fecha_publicacion')


def enviarcomentario(request):
    a = request.GET.get('valor')
    v = [a]

    if request.method == 'POST':
        us = request.POST['usuario']
        c = request.POST['cur']
        if request.user.is_authenticated:
            name = request.session['nombre'] = request.user.nombre
        cal = request.POST['calific']
        com = request.POST['comentario']

        formulario = Comentario(user_id=us, curso_id=c,
                                nombre=name, calificacion=cal, comentario=com)
        formulario.save()
        return redirect('cursos')

    return render(request, 'core/enviarcomentario.html', {'variable': v})

prevencion/views.py
from django.shortcuts import render


def prevencion(request):
    return render(request, 'core/prevencion.html')

talleres/views.py
from django.shortcuts import render
from .models import Talleres
from django.views.generic import DetailView


def talleres(request):
    if request.user.is_authenticated:
        request.session['usuario']=request.user.id
    tal=Talleres.objects.all()
    return render(request, 'core/talleres.html',{'tal':tal})

class Detalletaller(DetailView):
    model = Talleres
    template_name = 'core/informacion_taller.html'

core/templates/core/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>T-Social Med</title>

    <!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MB7HJ8K');</script>
        <!-- End Google Tag Manager -->
    

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
        rel="stylesheet" />
    <link
        href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@700&display=swap" rel="stylesheet">

    <!-- Core theme CSS (includes Bootstrap) iconos-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Estilos-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/estilo_template.css' %}" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'core/css/estilo_web.css' %}?v={{var1}}" />



</head>

<body id="page-top">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MB7HJ8K"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->

    <!-- AVISO COOKIES -->
    <div class="aviso-cookies" id="aviso-cookies">
		<img class="galleta" src="{% static 'core/img/cookie.svg' %}" alt="Galleta">
		<h3 class="titulo">Cookies</h3>
		<p class="parrafo">Utilizamos cookies propias y de terceros para mejorar nuestros servicios.</p>
		<button class="boton" id="btn-aceptar-cookies">De acuerdo</button>
		<a class="enlace" href="/aviso_cookies/">Aviso de Cookies</a>
	</div>
	<div class="fondo-aviso-cookies" id="fondo-aviso-cookies"></div>

	<script src="{% static 'core/js/aviso_cookies.js' %}"></script>
     <!-- FIN AVISO COOKIES -->



    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container-fluid">
            <a href="/">
                <img href="/" src="{% static 'core/img/logo.png' %}" class="img-fluid img_logo" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="bi-list"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav link-nav">
                    <li class="nav-item"><a class="nav-link me-lg-3" href="/">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="/docentes/">Docentes</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">Oferta formativa</a>
                        <ul class="dropdown-menu sub_menu">
                            <li><a class="dropdown-item" href="/cursos/">Cursos</a></li>
                            <li><a class="dropdown-item" href="/talleres/">Talleres On-line</a></li>
                            <li><a class="dropdown-item" href="/prevencion/">Prevención</a></li>
                        </ul>
                    </li>

                    <li class="nav-item"><a class="nav-link me-lg-3" href="/contacto/">Contacto</a></li>


                    <!-- Barra de búsqueda-->
                    <li class="nav-item">
                        <form action="/cursos/" method="POST">
                            {% csrf_token %}
                            <div class="bg-light rounded rounded-pill shadow-sm barra_busqueda">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button id="button-addon2" type="submit" class="btn btn-link color_lupa">
                                            <i class="fa fa-search"></i></button>
                                    </div>
                                    <input name="txt_busqueda" type="search" placeholder="Buscar"
                                        aria-describedby="button-addon2" class="form-control border-0 bg-light">
                                </div>
                            </div>
                        </form>
                    </li>
                    <!-- Fin barra de búsqueda-->

                </ul>
            </div>
            <!-- Botón inicio de sesion-->
            <div class="user-button">
                {% if user.is_authenticated %}
                <!-- Menú desplegable para usuarios autenticados -->
                <div class="dropdown">
                    <button class="rounded-button orange-button dropdown-toggle" type="button" id="userDropdown"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile_pic.url }}" class="img_usuario" style="color: #fff; font-size: 30px;"
                            loading="lazy">
                        <span class="text-inicio-sesion">{{ user.nombre }}</span>
                    </button>
                    <ul class="dropdown-menu mask-custom" aria-labelledby="userDropdown">

                        {% if user.is_authenticated and user.is_staff %}
                        <li><a class="dropdown-item nav-link-2" href="/admin/">Panel de Administración</a></li>
                        {% endif %}

                        <li><a class="dropdown-item nav-link-2" href="{% url 'users:perfil_usuario' %}">Perfil de
                                usuario</a></li>
                        <li><a class="dropdown-item nav-link-2" href="{% url 'users:logout' %}">Cerrar Sesión</a></li>

                    </ul>
                </div>
                {% else %}
                <!-- Botón de inicio de sesión para usuarios no autenticados -->
                <a href="{% url 'users:inicio_sesion' %}" class="user-button2">
                    <button class="rounded-button orange-button">
                        <i class="fas fa-circle-user user-icon"></i>
                        <p class="text-inicio-sesion">Iniciar Sesión</p>
                    </button>
                </a>
                {% endif %}
            </div>
            <!-- Fin botón inicio de sesion-->
        </div>
    </nav>
    <!-- Fin Nav Bar-->

    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

    <!-- Inicio Contenido-->
    <section>


        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}


        {% block contenido%}{% endblock %}
    </section>
    <!-- Fin Contenido-->

   
    <!-- Footer-->
    <footer class="text-center py-4">
        <div class="container px-5">
            <div class="text-white-50 small">
                <div class="mb-2 texto_footer">&copy; T-Social Med 2023. Todos los derechos reservados.</div>
                <a target="_blank" href="https://www.instagram.com/tsocialmed/">
                    <img class="img_rrss" src="{% static 'core/img/instagram.png' %}"></a>
                <span class="mx-1">&middot;</span>
                <a target="_blank" href="https://es.linkedin.com/company/social-med">
                    <img class="img_rrss" src="{% static 'core/img/linkedin.png' %}"></a>
                <span class="mx-1">&middot;</span>
                <img class="img_rrss" src="{% static 'core/img/email.png' %}">
                <span class="mx-1 texto_footer">&middot;</span>
                <img class="img_rrss" src="{% static 'core/img/phone.png' %}">
            </div>
        </div>
    </footer>
    <!-- jquery-3.7.1-->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- sweetalert JS-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"></script>

    <!-- general JS-->
    <script src="{% static 'core/js/general.js' %}"></script>
    <!-- Core theme JS
    <script src="js/scripts.js"></script>-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>-->


</body>

</html>

core/templates/core/charlas.html
{% extends 'core/base.html' %}

core/templates/core/comentarios.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<section style="margin-top: 8%; margin-bottom: 4%;">
    
    {% for com in object_list %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8 mx-auto">
        
                <div class="cards">
                    <div class="card-body informacion-curso" style="margin-top: 2%; margin-bottom: 1%;">            
                        <div class="d-flex align-items-center justify-content-between mb-1">
                            <h5 class="card-title mb-0 calificacion-title">Calificación</h5>
        
                            <div class="d-flex align-items-center stars">
                                <i class="fas fa-star mr-1 text-warning mr-1" data-rating="1"></i>
                                <i class="fas fa-star mr-1 text-warning mr-1" data-rating="2"></i>
                                <i class="fas fa-star mr-1 text-warning mr-1" data-rating="3"></i>
                                <i class="fas fa-star mr-1 text-warning mr-1" data-rating="4"></i>
                                <i class="fas fa-star text-warning" data-rating="5" ></i>
                            </div>
                        </div>

                        <div class="published_by d-flex flex-wrap align-items-center justify-content-start mb-1">
                            <p class="mr-1 mb-0">Publicado por:</p>
                            <p class="mb-0 publish-person">{{ com.user }}</p>
                        </div>

                        <div class="form-grupo mt-1 comentario-container" style="word-wrap: break-word; overflow: hidden;">
                            <p class="comentario">{{ com.comentario }}</p>
                            <p class="fecha-hora" style="color: #F1862A; position: absolute; bottom: 5px; right: 7%; font-size: 90%;">
                                {{ com.fecha_publicacion|date:"F j, Y H:i"|capfirst }}
                            </p>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</section>

{% endblock %}

core/templates/core/enviarCorreoContacto.html
<!DOCTYPE html>
<html>


<body>
    <div>
        <p><strong>{{ datos_formulario.nombre }}</strong> ha enviado un mensaje a T Social | Med.</p>
        <p>Su dirección de correo electrónico es: {{ datos_formulario.email }}</p>
        <p>Mensaje: <strong>{{ datos_formulario.mensaje }}</strong></p>
        <p>¡No dudes en contactarte con él/ella!</p>
    </div>
</body>
</html>

core/templates/core/oferta_formativa.html
{% extends 'core/base.html' %}