t_social_med/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views
from cursos import views as cursos_views
from talleres import views as talleres_views
from prevencion import views as prevencion_views
from cursos.views import Detalle
from cursos.views import Coment
from talleres.views import Detalletaller
from cursos.views import enviarcomentario
from users import views as users_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',
         core_views.home, name='Home'),
    path('', include('users.urls', namespace='users')),
    path('olvidar_contrasena/', core_views.olvidar_contrasena,
         name='olvidar_contrasena'),
    path('recuperar_clave/', core_views.recuperar_clave, name='recuperar_clave'),
    path('contacto/', core_views.contacto, name='contacto'),
    path('docentes/', core_views.docentes, name='docentes'),
    path('cursos/', cursos_views.cursos, name='cursos'),
    path('talleres/', talleres_views.talleres, name='talleres'),
    path('prevencion/', prevencion_views.prevencion, name='prevencion'),
    path('informacion_curso/<int:pk>/',
         Detalle.as_view(), name='informacion_curso'),
    path('confirmacion_curso/', cursos_views.confirmacion,
         name='confirmacion_curso'),
     path('informacion_taller/<int:pk>/',Detalletaller.as_view(),name='informacion_taller'),
    path('enviar_correo_contacto/', core_views.enviar_correo_contacto,
         name='enviar_correo_contacto'),
    path('inicio_sesion/', users_views.inicio_sesion, name='inicio_sesion'),
    path('form_registro/', users_views.registro, name='form_registro'),
    path('eliminar_cuenta/', core_views.eliminar_cuenta, name='eliminar_cuenta'),
    path('registrar_datos/', users_views.signup_view, name='registrar_datos'),
    path('aviso_cookies/', core_views.aviso_cookies, name='aviso_cookies'),
    path('comentarios/', Coment.as_view(), name='comentarios'),
    path('enviarcomentario/', cursos_views.enviarcomentario,
         name='enviarcomentario'),
    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('inicio_sesion/', views.inicio_sesion, name='inicio_sesion'),
    path('login/', views.login_view, name='login'),
    path('form_registro/', views.registro, name='form_registro'),
    path('signup/', views.signup_view, name='signup'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('logout/', views.logout_view, name='logout'),
]

core/models.py
from django.db import models
# aca se importa el username interno de django
from django.contrib.auth.models import User
from datetime import datetime
from users.models import UserProfile


class Usuarios(models.Model):
    username = models.OneToOneField(
        UserProfile, verbose_name="username", on_delete=models.CASCADE, null=False)
    nombre = models.CharField(max_length=40, verbose_name="Nombre", null=False)
    apellido = models.CharField(
        max_length=40, verbose_name="Apellidos", default="Apellido", null=False)
    nac = models.DateField(verbose_name="Fecha de Nacimiento",
                           default=datetime.now, null=False)
    zona = models.CharField(
        max_length=20, verbose_name="Ciudad", default='zona', null=False)
    correo = models.EmailField(
        max_length=30, verbose_name="Direccion de correo", null=False)
    telefono = models.CharField(
        max_length=20, verbose_name="Numero Telefonico", null=False)
    imagen = models.ImageField(
        upload_to='media/', verbose_name="Imagen", null=True)
    trabajo = models.CharField(
        max_length=30, verbose_name="Ocupacion", default="Ocupacion", null=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

users/forms.py
from django import forms


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'loginEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'loginPassword',
            'type': 'password',
            'class': 'form-control',
        })
    )


class UserSignUpForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'signupEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    nombre = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    apellido = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    fecha_nacimiento = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control'
            }
        ))

    telefono = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'type': 'integer',
                'class': 'form-control'
            }
        ))

    nacionalidad = forms.ChoiceField(
        choices=[
            ('', 'Seleccione...'),
            ('española', 'Española'),
            ('extranjera', 'Extranjera'),
        ],
        widget=forms.Select(
            attrs={
                'class': ''}),
    )

    ciudad = forms.CharField(
        max_length=100,
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    ocupacion = forms.CharField(
        max_length=100,
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'signupPassword',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control'
            }
        ))

    # comprueba que el password2 es el requerido
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['password2']

core/views.py
import time

from django.shortcuts import render, redirect
from django.http import HttpResponse
from t_social_med.enviarCorreo import funcionEnviarCorreo, enviarCorreoContacto, funcionRecuperarPassword
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.conf import settings
from django.shortcuts import render



def home(request):
    # capturamos la id del usuario que se logee en la pagina
    request.session['usuario'] = request.user.id
    usuario_autenticado = request.user.is_authenticated
    var1 = time.time()

    data = {
        'titulo': 'titulo correo',
        'correoDestino': ['vravest@gmail.com'],
        'curso': 'manejo de la ira',
    }

    return render(request, 'core/home.html', {'var1': var1, 'usuario_autenticado': usuario_autenticado})


def contacto(request):
    if request.user.is_authenticated:
        request.session['usuarionombre'] = request.user.nombre
        request.session['usuarioCorreo'] = request.user.email
    var1 = time.time()
    return render(request, 'core/contacto.html', {'var1': var1})


def docentes(request):
    var1 = time.time()
    return render(request, 'core/docentes.html', {'var1': var1})


def olvidar_contrasena(request):
    if request.method == 'POST':
        destinatario = {
            'email': request.POST.get('ingCorreo', ''),
        }
        funcionRecuperarPassword(destinatario)
        return HttpResponse("Correo enviado.")
    else:
        return render(request, 'core/olvidar_contrasena.html')

    var1 = time.time()
    return render(request, 'core/olvidar_contrasena.html', {'var1': var1})


def recuperar_clave(request):
    var1 = time.time()
    return render(request, 'core/recuperar_clave.html', {'var1': var1})


# def informacion_curso(request):
#     var1 = time.time()
#     return render(request, 'core/informacion_curso.html', {'var1': var1})




def enviar_correo_contacto(request):
    if request.method == 'POST':
        datos_formulario = {
            'nombre': request.POST.get('txtName', ''),
            'email': request.POST.get('txtEmail', ''),
            'mensaje': request.POST.get('txtMsg', ''),
        }
        enviarCorreoContacto(datos_formulario)
        return JsonResponse({'message': 'Correo enviado correctamente. Gracias por contactarnos.'})
    else:
        return render(request, 'core/contacto.html')

    

@login_required
def eliminar_cuenta(request):
    if request.method == 'POST':
        try:
            user = request.user
            user.delete()

            # Envía una respuesta JSON indicando éxito
            return JsonResponse({'title': 'Éxito', 'message': 'Tu cuenta ha sido eliminada exitosamente.', 'icon': 'success'})
        except Exception as e:
            return JsonResponse({'title': 'Error', 'message': f'Ocurrió un error: {str(e)}', 'icon': 'error'})

    return render(request, 'users/eliminar_cuenta.html')


def reportes(request):
    var1 = time.time()
    return render(request, 'core/reportes.html', {'var1': var1})




def aviso_cookies(request):
    var1 = time.time()
    return render(request, 'core/aviso_cookies.html', {'var1': var1})

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
import time
import json
import os
from django.contrib.staticfiles import finders
from django.conf import settings
from core.models import Usuarios

from .forms import UserLoginForm, UserSignUpForm


def inicio_sesion(request):
    var1 = time.time()
    return render(request, 'users/inicio_sesion.html', {'var1': var1})


@login_required(login_url='Home')
def perfil_usuario(request):
    var1 = time.time()
    request.session['usuarioNombre'] = request.user.nombre
    request.session['usuarioApellido'] = request.user.apellido
    request.session['usuarioCorreo'] = request.user.email
    request.session['usuarioTelefono'] = request.user.telefono
    request.session['usuarioNacionalidad'] = request.user.nacionalidad
    request.session['usuarioCiudad'] = request.user.ciudad
    request.session['usuarioOcupacion'] = request.user.ocupacion

    return render(request, 'users/perfil_usuario.html', {'var1': var1})


def registro(request):
    var1 = time.time()
    usuario_autenticado = request.user.is_authenticated
    print(usuario_autenticado)
    if usuario_autenticado:

        # Almacena los valores en la sesión
        request.session['var1'] = var1
        request.session['usuario_autenticado'] = usuario_autenticado
        return redirect('Home')

    else:
        return render(request, 'users/form_registro.html', {'var1': var1})


def login_view(request):
    login_form = UserLoginForm(request.POST or None)

    if request.method == 'GET':
        print("entre aqui")
        return redirect('inicio_sesion')

    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        print("fin logn 1")
        if user is not None:
            login(request, user)
            messages.success(request, 'Has iniciado sesión correctamente')
            return redirect('cursos')

        else:
            messages.warning(
                request, 'Correo electrónico o contraseña invalida')
            return redirect('inicio_sesion')
    else:
        messages.error(request, 'Formulario invalido')
        print("entre home 1")
        return redirect('Home')


def obtener_label_ciudad(ciudad_code):
    try:

        if ciudad_code == "ninguna":
            return ciudad_code
        # Utiliza finders para encontrar la ruta del archivo en la carpeta static
        file_path = finders.find(f'core/data/provincias.json')
        with open(file_path, 'r') as f:
            ciudades_data = json.load(f)
        for ciudad in ciudades_data:
            if ciudad['code'] == ciudad_code:
                return ciudad['label']
    except FileNotFoundError:
        return None


def obtener_label_ocupacion(ocupacion_code):
    try:
        # Utiliza finders para encontrar la ruta del archivo en la carpeta static
        file_path = finders.find(f'core/data/profesiones.json')
        with open(file_path, 'r') as f:
            ocupaciones_data = json.load(f)
        for ocupacion in ocupaciones_data['ocupaciones']:
            if ocupacion['code'] == ocupacion_code:
                return ocupacion['label']
    except FileNotFoundError:
        return None


def signup_view(request):
    var1 = time.time()

    if request.method == 'GET':
        print("entre aqui")
        return redirect('form_registro')

    if request.method == 'POST':
        signup_form = UserSignUpForm(request.POST or None)

        if signup_form.is_valid():

            nombre = signup_form.cleaned_data.get('nombre')
            apellido = signup_form.cleaned_data.get('apellido')
            fecha_nacimiento = signup_form.cleaned_data.get('fecha_nacimiento')
            email = signup_form.cleaned_data.get('email')
            password = signup_form.cleaned_data.get('password')
            telefono = signup_form.cleaned_data.get('telefono')
            nacionalidad = signup_form.cleaned_data.get('nacionalidad')
            ciudad_code = signup_form.cleaned_data.get('ciudad')
            ocupacion_code = signup_form.cleaned_data.get('ocupacion')

            ciudad_label = obtener_label_ciudad(ciudad_code)
            ocupacion_label = obtener_label_ocupacion(ocupacion_code)

            if ciudad_label is None or ocupacion_label is None:
                return JsonResponse({'detail': 'Error al obtener etiquetas'})

            if nacionalidad == 'extranjera':
                # Si la nacionalidad es extranjera, puedes hacer que el campo ciudad sea opcional
                ciudad = None

            try:
                user = get_user_model().objects.create(
                    nombre=nombre,
                    apellido=apellido,
                    fecha_nacimiento=fecha_nacimiento,
                    email=email,
                    password=make_password(password),
                    telefono=telefono,
                    nacionalidad=nacionalidad,
                    ciudad=ciudad_label,
                    ocupacion=ocupacion_label,
                    is_active=True
                )
                print(user)
                login(request, user)

                return redirect('cursos')

            except Exception as e:
                print(e)
                return JsonResponse({'detail': f'{e}'})
        else:
            print("formulario no valido")
            messages.warning(request, 'formulario no valido')
            return redirect('form_registro')


def logout_view(request):
    logout(request)
    return redirect('Home')


# @login_required(login_url='Home')
# def profile_view(request):
#     return render(request, '/perfil_usuario/')

core/templates/users/eliminar_cuenta.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}
    <h2>Eliminar Cuenta</h2>
    <p>¿Estás seguro de que deseas eliminar tu cuenta?</p>
    <form method="post" action="{% url 'eliminar_cuenta' %}">
        {% csrf_token %}
        <!-- Resto del formulario aquí -->
        <button type="submit" class="rounded-button orange-button" id="btn_eliminar_cuenta">
            <i class="fa-solid fa-trash-can mr-2 btnEliminarCuenta"></i>
            <p class="text-inicio-sesion">Eliminar cuenta</p>
        </button>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
{% endblock %}

core/templates/users/form_registro.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido%}
<div class="container__prime_">
    <img src="{% static 'core/img/logo.png' %}" class="img_logo_is" alt="logo">
    <div class="container__form">
        <form action="{% url 'users:signup'%}" class="form" method="POST" onsubmit="return validarFormulario()">
            {% csrf_token %}
            <div class="form__register">

                <div class="nombre-container">
                    <i class="fa-solid fa-user icon_is"></i>
                    <input type="text" name="{{ signupForm.nombre.name }}" placeholder="Ingrese nombre" class="text" required>
                </div>

                <div class="apellido-container">
                    <i class="fa-solid fa-user icon_is"></i>
                    <input type="text" name="{{ signupForm.apellido.name }}" placeholder="Ingrese apellido" class="text" required>
                </div>

                <div class="nacimiento-container">
                    <i class="fa-solid fa-calendar icon_is"></i>
                    <input type="date" name="{{ signupForm.fecha_nacimiento.name }}"  class="date" required>
                </div>

                <div class="correo-container">
                    <i class="fa-solid fa-envelope icon_is"></i>
                    <input type="email" name="{{ signupForm.email.name }}" placeholder="Ingrese correo electrónico" class="correo" required>
                </div>

                <div class="contraseña-container">
                    <i class="fa-solid fa-lock icon_is"></i>
                    <input type="password" name="{{ signupForm.password.name }}" placeholder="Ingrese contraseña" class="password" required>
                </div>

                <div class="contraseña-container">
                    <i class="fa-solid fa-lock icon_is"></i>
                    <input type="password" name="{{ signupForm.password2.name }}" placeholder="Confirmar contraseña" class="password" required>
                </div>

                <div class="telefono-container">
                    <i class="fa-solid fa-phone icon_is" ></i>
                    <input type="number" name="{{ signupForm.telefono.name }}" placeholder="Ingrese número de teléfono" class="number" required>
                </div>

                <div class="nacionalidad-container">
                    <i class="fa-solid fa-location-dot icon_is"></i>
                    {{ signupForm.nacionalidad }}
                </div>

                <div class="ciudad-container" id="divCiudad">
                    <i class="fa-solid fa-location-dot icon_is"></i>
                    <select name="{{ signupForm.ciudad.name }}" id="ciudad">
                        <option value="" selected>Seleccione su provincia</option>
                        {% for provincia in provincias_data %}
                        <option value="{{ provincia.value }}">{{ provincia.label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="ocupacion-container" id="divOcupacion">
                    <i class="fa-solid fa-briefcase icon_is"></i>
                    <select name="{{ signupForm.ocupacion.name }}" id="profesiones" required>
                        <option value="" disabled selected>Seleccione su ocupación</option>
                        {% for ocupacion in ocupaciones_data %}
                        <option value="{{ ocupacion.value }}">{{ ocupacion.label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-check onlinecheckbox">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <a data-bs-toggle="modal" data-bs-target="#tycModal">
                    <label class="form-check-label" for="flexCheckDefault">
                      He leído y acepto los <a> términos y condiciones.</a>
                    </label>
                </div>
                <p class="text_register">Al registrarme acepto que T-Social Med trate mis datos personales para la gestión de la inscripción, así como enviarme información relativa a la misma y cualquier otro relacionado con acciones formativas de mi interés.</p>
                <button  class="myButton_registro">REGISTRARSE</button>            

                <p1>¿Ya estás registrado?<a class="volver" href="{% url 'users:inicio_sesion' %}">Iniciar sesión</a></p1>                

        </form>
    </div>
</div>
<script src="{% static 'core/js/form_registro.js' %}?v={{var1}}"></script>

{% endblock %}

core/templates/users/inicio_sesion.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido%}



<div class="login">
    <div class="login-screen">
        <div>
            <div class="contact-form-wrapper d-flex justify-content-center">

                <form method="post" accept-charset="utf-8" action="{% url 'users:login' %}" class="contact-form">
                    {% csrf_token %}

                    <div class="contenedor_contacto">
                        <div class="contenedor_logo">
                            <img src="{% static 'core/img/logo.png' %}" class="img-fluid img_logo_is" alt="logo">
                        </div>
                        <div>
                            <i class="fa-solid fa-user icon_is"></i>
                            <input type="text" name="email" class="txt_box input_is" placeholder="Usuario" required>
                        </div>
                        <div>
                            <i class="fa-solid fa-lock icon_is"></i>
                            <input type="password" name="password" class="txt_box input_is" placeholder="Contraseña" required>
                        </div>
                
                        <div class="contenedor_boton">
                            <input type="submit" value="ACCEDER" class="btn_ingresar">
                        </div>



                        <div class="contendor_txt_sub">
                            <span class="txt_is">¿Es la primera vez que usas T-Social Med?</span>
                        </div>
                        <div class="contendor_link_sub">
                            <span><a href="/form_registro/" class="txt_is">Regístrate</a></span>
                        </div>
                        <div class="contenedor_contrasena_olvidada">
                            <span><a href="/olvidar_contrasena/" class="txt_is">¿Olvidaste tu contraseña?</a></span>
                        </div>

                    </div>
                </form>
            </div>
        </div>
        </form>
        {% endblock %}

core/templates/users/perfil_usuario.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido%}

<div class="container cont_perfil">
    <div class="row">


        <div class=" col-md-5 col-12 form-group">
            <div class="cont_dos">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="cont_titulo">
                            <span>PERFIL DE USUARIO</span>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row m-t-40">
                        <div class="col-sm-3 "></div>
                        <div class="col-sm-9 form-group">
                            <span class="txt_subtitulo">Información básica</span>
                        </div>
                    </div>
                   
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Nombre</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioNombre }}" class="txt_box_perfil" required>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Apellido</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioApellido }}" class="txt_box_perfil" required>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Correo</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioCorreo }}" class="txt_box_perfil" required>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Teléfono</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioTelefono }}" class="txt_box_perfil" required>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Nacionalidad</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioNacionalidad }}" class="txt_box_perfil" required>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Ciudad</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioCiudad }}" class="txt_box_perfil" required>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-3 col-xs-2 text-center2">
                            <div class=""><span class="txt_perfil">Ocupación</span></div>
                        </div>
                        <div class="col-sm-8 col-xs-10">
                            <input type="text" value="{{ request.session.usuarioOcupacion }}" class="txt_box_perfil" required>
                        </div>
                    </div>

                    <div class="row mt-auto p-b-10">
                        <div class="col-sm-12">
                            <div class="cont_boton">
                                <form method="post" action="/eliminar_cuenta/">
                                    {% csrf_token %}
                                    <button class="rounded-button orange-button" type="button" id="btn_eliminar_cuenta">
                                        <i class="fa-solid fa-trash-can mr-2"></i>
                                        <p class="text-eliminar-cuenta">Eliminar cuenta</p>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<script src="{% static 'core/js/rendered-js.js' %}"></script>


{% endblock %}

core/templates/users/terminos_condiciones.html
<!-- Modal -->
<div class="modal fade" id="tycModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">

                


              

            </div>
        </div>
    </div>
</div>